language: ruby
sudo: false

rvm:
- ruby-head
- 2.4.0
- 2.3.3
- 2.2.6
- 2.1.10
- 2.0
- 1.9.3
- jruby-head
- jruby-9.0.5.0

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: 1.9.3
    - rvm: 2.0
